meta_name: "SwiftSports"
meta_title: "SwiftSports"
meta_description: "There is ability to play sports everywhere for everyone!"
meta_image: "ogimage.jpeg" #should exist in `app/assets/images/`
meta_product_name: "Application for Social Sports"
twitter_account: "@your_twitter_account"   # required for Twitter Cards
